### PR TITLE
added FAQs section in home page

### PR DESCRIPTION
**Pull request by Lemon1903**
### Changes includes:
- added the `FAQS.tsx` in `components/Home` for the FAQs section in home page
- modifed and refactored `Accordion.tsx`

### CODE REVIEW

**Review by Karmotrine — CHANGES_REQUESTED** [review]
Functionality wise it's all good but I think here are some minor features that are not present in the component.

1. I think its possible to change the appearance of the current opened item via `.AccordionTrigger[data-state='open]` . [Example](https://www.radix-ui.com/primitives/docs/components/accordion#rotated-icon-when-open) 
Hence we can implement rotating buttons and adding gradient into the current open item's background.
image

2. Y-axis gap between accordion items: Maybe increase the gap between them by a bit. I see on my side that it is currently around `20px` but the low-fi suggests it to be around `51px`

**Comment by Lemon1903** [comment]
> Hence we can implement rotating buttons and adding gradient into the current open item's background.

Oh yeah I removed the chevron button and the rotating transform transition in the `Accordion.tsx` component since our lofi designs doesn't use them. It is also to give more freedom to the user of the component on how he/she will implement that button. But in this case? How will I implement the rotating buttons? Like the plus button will rotate and fade out then the minus button would rotate back and fade in?

Also I didn't focus that much on the background color and gradient since it's still in lofi and would highly be changed in hifi design. Should I still add the gradient knowing that it would be changed in the hifi design?

> Y-axis gap between accordion items: Maybe increase the gap between them by a bit. I see on my side that it is currently around 20px but the low-fi suggests it to be around 51px

Ahh yeah, my mistake with the gap, it's in `16px` instead of `30px` gap _(base on figma)._ I also used the `space-y-7` tw class which is equivalent to `28px` gap since there is no `30px` if that's ok? I refrain from using arbitrary values that much and use only the closest tw class to that one instead

**Comment by Karmotrine** [comment]
> How will I implement the rotating buttons? Like the plus button will rotate and fade out then the minus button would rotate back and fade in?

I agree on the first two points, but its not really on the `ChevronDownIcon` component rather it is on how it was implemented on the radix-ui example. I suggest trying `[&[data-state=open]>#plus]:rotate-45` on `<AccordionTrigger>` instead of using two different icon components and switching their visibilities, plus adding `transform-300` to `<Plus />`

> Should I still add the gradient knowing that it would be changed in the hifi design?

It's okay not to implement it at this point.

> I refrain from using arbitrary values that much and use only the closest tw class to that one instead

We need to include this to contributor notes if ever so that we can all agree to one method.

**Review by Karmotrine — CHANGES_REQUESTED** [review]
I suggest trying `[&[data-state=open]>#plus]:rotate-45` on `<AccordionTrigger>` instead of using two different icon components and switching their visibilities, plus adding `transform-300` to `<Plus />`

**Review by Karmotrine — APPROVED** [review]

**Pull request merged**
