### PR TITLE
created a section of the About page: our alumnis

### PR DESCRIPTION
**Pull request by shaniassi**
**Changes includes:**

- add: components/About/OurAlumnis - new page.
- modify: pages/About - imports a new component.

### CODE REVIEW

**Review by Lemon1903 — COMMENTED** [review]
Alright the page loads the section very similar to the lofi design. First of all there are merge conflicts again, kindly pull the latest changes in `dev` branch and resolve the conflicts on your side first (mainly its on benefits section, I think you accidentally push your other changes from another branch to this branch)

Then I have a question regarding the unknown classes you added in `classNames`. Those are classes starting with `frame`, etc. What does they stand for and their uses? Or did you forget to remove them from your testing?

Not sure if there are still changes needed to be done for now or stay as is and wait for the hifi ones before starting the interactivity, what do you think @Karmotrine about this one?

**Comment by Karmotrine** [comment]
> Not sure if there are still changes needed to be done for now or stay as is and wait for the hifi ones before starting the interactivity, what do you think @Karmotrine about this one?

I think we can put interactivity as long as there will be no major changes to the Lo-fi design. 🙏

**Comment by shaniassi** [comment]
Hi! I apologize, I forgot to remove the frames. I added them for my reference since I'm sometimes confused about which frame I'm working on. I'll remove them right now. Thanks!

**Comment by shaniassi** [comment]
> Then I have a question regarding the unknown classes you added in `classNames`. Those are classes starting with `frame`, etc. What does they stand for and their uses? Or did you forget to remove them from your testing?

Hi! I apologize, I forgot to remove them. I added them for my reference since I'm sometimes confused about which frame I'm working on. I'll remove them right now. Thanks!

**Comment by Karmotrine** [comment]
> Hi! I apologize, I forgot to remove them. I added them for my reference since I'm sometimes confused about which frame I'm working on. I'll remove them, but I just want to clarify if it is alright to make changes?

Yup, just modify + push to the same branch.

**Comment by shaniassi** [comment]
**Changes include:**

- removed the unknown classes

**Review by Karmotrine — APPROVED** [review]
LGTM

**Pull request merged**
