### PR TITLE
Added devskolar requirement and process section #30

### PR DESCRIPTION
**Pull request by Java-rice**
Changes Includes:
- [added process box component] -- components/Devskolar/ProcessBox.tsx
- [added process section] -- components/Devskolar/Process.tsx
- [added requirement bars component] -- components/Devskolar/RequirementBars.tsx
- [added requirement section] -- components/Devskolar/Requirements.tsx
- [added sample placeholder2 based on Figma Lofi]

### CODE REVIEW

**Comment by Lemon1903** [comment]
Sorry bout the confusion about the branch where to make the pull request in the `README.md` file as it is not yet updated. It should be in the `dev` branch instead of the `main` branch since `dev` branch was for frontend and `main` was for the backend team

**Comment by Lemon1903** [comment]
There are some errors when I opened and run this branch. Mainly in `Process.tsx` and `Requirements.tsx`, please resolve those problems.

Also can you use `export default function <ComponentName>(props: <PropsInterface>)` format for components instead of using `const <ComponentName>: React.FC<PropsInterface>`? This will make the format consistent with how other components are defined

**Comment by Java-rice** [comment]
I see, sorry, I forgot to import Requirements.tsx on the register page, and sure, I'll change the way components are defined. Thank you

**Comment by Java-rice** [comment]
Changes Includes:

- [added process box component] -- components/Devskolar/ProcessBox.tsx
- [added process section] -- components/Devskolar/Process.tsx
- [added requirement bars component] -- components/Devskolar/RequirementBars.tsx
- [added requirement section] -- components/Devskolar/Requirements.tsx
- [added sample placeholder2 based on Figma Lofi]

New Changes Includes
-[added requirement section to register page]
-[modify how the components are defined]

**Pull request closed without merging**
