### PR TITLE
Add hero section to the Events page

### PR DESCRIPTION
**Pull request by Viadsss**
**Changes includes:**
- Add `eventsHero.tsx` for hero section of Events page

**Questions/Issues:**
- I'm having an issue with using the url of the placeholder.img in the public folder. So I tried to use the image source file in figma. Okay lang po ba yun?

**Tasks to do:**
- Keep up the section to the Mid Fidelity

### CODE REVIEW

**Review by Karmotrine — CHANGES_REQUESTED** [review]
1. Please rename `eventsHero.tsx` to `events`
2. Use `next/Image` component for the background image `<div>`. See: https://www.youtube.com/watch?v=rb6fOQ4LfrE

**Comment by Viadsss** [comment]
**Changes includes:**
- Renamed the `eventsHero.tsx` to `events.tsx
- Used the `next/Image` component to change the background image
- Imported ArrowDown component from phosphor to change the arrow svg

**Review by Karmotrine — CHANGES_REQUESTED** [review]
@Viadsss This is great overall but as a last thing to do for code organization, please make the whole section as another component inside `events.tsx`. For example: `events.tsx` should look like this:

```jsx

import EventsHero from "@/components/Events/EventsHero.tsx";

export default function EventsPage() {
   return (
       <>
           <EventsHero />
       </>
   )
}
```

And the current contents of `events.tsx` in `pages` folder should be relocated inside a separate file `EventsHero.tsx` (as a separate component) inside `components/Events` path folder. Something like:

```jsx
export default function EventsHero() {
   return (
     <>
        {/* Insert current contents of `pages/events.tsx` file here... */}
     </>
   )
}
```

**Comment by Viadsss** [comment]
🛠️ Changes includes update:

- Add `components/Events` path folder and moved the original content of `events.tsx` file to it and named it as `EventsHero.tsx`
- Modify the `pages/events.tsx` content to as another component named the component `EventsPage()` and import the `EventsHero.tsx` inside it

**Review by Karmotrine — APPROVED** [review]
LGTM

**Pull request merged**
