### PR TITLE
created latest events section

### PR DESCRIPTION
**Pull request by Lemon1903**
### Changes includes:
- made `LatestNewsPreview.tsx` reusable component for **Latest News** page.
- added `Placeholder1.png` for the `LatestNewsPreview` component
- cleaned `pages/index.tsx`
- removed `api` folder as it is not needed anymore
> Note: current implementation of `LatestNewsPreview` component may be changed as stated in figma

### CODE REVIEW

**Comment by Lemon1903** [comment]
There are new changes sa part na to sa figma and will work on it first muna

**Review by Karmotrine — CHANGES_REQUESTED** [review]
`<section>` container of `<HeroCarousel />` in `index.tsx` has issues of having a whitespace below it. A fix can be done by modifying `className` into `min-h-[calc(100vh-4rem)]`

**Comment by Lemon1903** [comment]
> `<section>` container of `<HeroCarousel />` in `index.tsx` has issues of having a whitespace below it. A fix can be done by modifying `className` into `min-h-[calc(100vh-4rem)]`

### New changes includes:
- rewrite the `LatestNewsPreview.tsx` into a single component only
- modified `HeroCarousel.tsx` to fix the problem with the whitespace below it
- added `LatestNewsSection.tsx` to abstract the section and added the carousel from the current design iteration
- removed `src/components/Home/index.tsx` since nothing is in there and the purpose of it is not specified

### Tasks to do:
- abstract carousel in `LatestNewsSection.tsx` into separate component and hook to make it more manageable and hide complexity
- fix the glitchy behavior when moving slides by touch

**Comment by Lemon1903** [comment]
Don't know what happened there but the commit history of this branch got changed tas bumalik yung old commits na tinaggal ko. Inayos ko lang ulit and there should only be 3 commits here

**Comment by Karmotrine** [comment]
> Don't know what happened there but the commit history of this branch got changed tas bumalik yung old commits na tinaggal ko. Inayos ko lang ulit and there should only be 3 commits here

I think I moved something. Sorry.

**Comment by Lemon1903** [comment]
### New changes includes:
Splitted `LatestNews.tsx` into separate components to handle separate concerns:
- `CarouselContext` now holds the slider and the slider context
- `CarouselSlide` now holds the calculation of its own style
- `CarouselNavigation` now holds everything related to navigation buttons

**Comment by Karmotrine** [comment]
I think finish touches would be enabling how to pass slides props to `LatestNews()` itself. 
Let's say we receive data from server in the JSON format of: 
```lang=json
{
    {
         img_url: "https://www.flickr.com/1",
         title: "Sample Title 1"
    },
    {
         img_url: "https://www.flickr.com/2",
         title: "Sample Title 2"
    },
}
```

I think we can make a mockData variable array for now.

**Review by Karmotrine — CHANGES_REQUESTED** [review]
Check my latest feedback

**Comment by Lemon1903** [comment]
> I think finish touches would be enabling how to pass slides props to `LatestNews()` itself. Let's say we receive data from server in the JSON format of:
> 
> ```
> {
>     {
>          img_url: "https://www.flickr.com/1",
>          title: "Sample Title 1"
>     },
>     {
>          img_url: "https://www.flickr.com/2",
>          title: "Sample Title 2"
>     },
> }
> ```
> 
> I think we can make a mockData variable array for now.

There would be no props to be passed to the `LatestNews` section component since the fetching would be handled internally so the complexity of fetching would be abstracted away from the `IndexPage` component.

I tried to recycle the `mockDataImage` array but the size doesn't fit the slide size so instead of creating a new mock data for the events preview carousel, I replaced the image props with random picsum image with the right dimensions. The only thing that would change in the code if we are fetching data already would be this part:

```
{[0, 1, 2, 3].map((idx) => (
  <CarouselSlide
    key={idx}
    title={`Slide ${idx}`}
    image={`https://picsum.photos/920/480?random=${idx}`}
    idx={idx}
  />
))}
```

So instead of mapping over a temporary array `[0, 1, 2, 3]`, it would map the data fetched from the backend. Then the `title` and `image` props would come from that fetched data.

**Review by Karmotrine — APPROVED** [review]
LGTM

**Pull request merged**
