### PR TITLE
Add  Info section to the Be a Devskolar Page

### PR DESCRIPTION
**Pull request by Viadsss**
**Changes Includes:**
- Add `devskolarInfo.tsx` for info section of Be a Devskolar Page
- Created a `BoxDecoration` component for the rectangle frames behind the main content

**Tasks to do:**
- Change the colors to keep up to the Mid Fidelity of Info section

### CODE REVIEW

**Review by Karmotrine — CHANGES_REQUESTED** [review]
1. Please use only the existing page for "Be a Devskolar" named `register.tsx`. E.g. for this task, you will be replacing the current `<HeroSection />` with something like `<DevskolarInfo />`
2. Please make a separate file for `DevskolarInfo` page function and `BoxDecoration` UI component function. Refer to the file structure of PR #42
3. Based on Figma, `BoxDecoration` is not totally centered. Removing `relative` from the main `<div>` in `DevskolarInfo` may help.

**Comment by Viadsss** [comment]
**Changes include update:**

**Comment by Viadsss** [comment]
**Changes includes updates:**

- Renamed the `devskolarInfo.tsx` to `Info.tsx`
- Created a seperate file for `BoxDecoration` and named it as `BoxDecoration.tsx`
- Created a Info folder inside the Devskolar Component folder and moved the `Info.tsx` and `BoxDecoration.tsx` into it
- Replaced the  current `<HeroSection />` into `<DevskolarInfo />` in the `register.tsx`

**Review by Karmotrine — CHANGES_REQUESTED** [review]
@Viadsss thanks for reorganizing the code but I've found a bug affecting `Info.tsx`, the culprit seems to be `BoxDecoration.tsx` specifically its main `<div>`'s width styling. It causes the page to have horizontal overflowing, hence the horizontal scroll being visible. Please look further into it.

Screenshot:
image

**Comment by Viadsss** [comment]
🛠️ Changes includes update:

- Modify the `BoxDecoration.tsx` to fix the horizontal overflowing
- Modify the `Info.tsx` to center the section when zooming


> Sorry po, di ko po siya napansin di po kasi halata ung horizontal bar sa firefox 🤣

**Review by Karmotrine — APPROVED** [review]
LGTM

**Pull request merged**
