### PR TITLE
Added CORS Headers for Backend Development

### PR DESCRIPTION
**Pull request by Pilner**
Commit#1: Added `.vscode` to the `.gitignore` file
Commit#2-3: Added `django-cors-headers` package

### CODE REVIEW

**Comment by JirroReo** [comment]
Please remove `.vscode` config file as it might conflict with others' vscode environments.

**Comment by Pilner** [comment]
In the `dev` branch, Yuan and the others have included the `.vscode` to the `.gitignore` file. Should I still remove it for the backend development?

**Comment by JirroReo** [comment]
Ah nevermind i misread, .vscode should actually be in the gitignore, i thought u committed your vscode config file. My bad. LGTM.

**Comment by JirroReo** [comment]
Merged.

**Pull request merged**
