### PR TITLE
Move hero section of homepage to aboutUs page and modify styling

### PR DESCRIPTION
**Pull request by xialuna**
### Changes includes:
- Moved hero section of home page _(`ShowcaseCarousel.tsx`)_ to aboutUs page based on the figma design
- Replaced the previous hero section of home page with:
```
<section className="min-h-screen">
        <h1 className="text-2xl underline">Mission Landing</h1>
 </section>
```
 - Changing text and margin of the text in `ShowcaseCarousel.tsx` based on the figma design

### CODE REVIEW

**Review by Lemon1903 — CHANGES_REQUESTED** [review]
Alright! This section is now in the right page and is still rendering right. There are some minor changes to make the code more readable. 

First of all, make sure to pull the latest commit from the `dev` branch since the About page have new commits that are merged already and then solve the conflicts

Could we change the `ShowcaseCarousel` name to something that would represent the section? Something like related to hero since this section is a hero section

**Comment by xialuna** [comment]
[UPDATE]
### Changes includes:
- Refactor className `{` `}` to normal strings
- Change` ShowcaseCarousel.tsx` to `AboutHero`
- Change some arbitrary classes to its tailwind counterpart _(Note: I was only able to change 1 (max width) since it was the only one I was able to find)_

**Review by Lemon1903 — CHANGES_REQUESTED** [review]
Almost done! The only changes need is to move the `AboutHero.tsx` into `components/About` since it is a section of the About page. Then there are still unanswered question on the last review, pls check those out thanks!

**Review by Lemon1903 — APPROVED** [review]
I added a refactoring commit above the last commit. 
### Changes includes:
- replacing the arbitrary classes with corresponding tw utility classes 
- moved the `AboutHero.tsx` to `components/About` folder as it is a section of About page not Home page

**Pull request merged**
